# Generated by Django 3.0.4 on 2020-05-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('myorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pastas',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='platters',
            field=models.ManyToManyField(blank=True, to='orders.Platter'),
        ),
        migrations.AddField(
            model_name='order',
            name='salads',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='subs',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
    ]
