# Generated by Django 3.0.4 on 2020-05-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0003_auto_20200501_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(blank=True),
        ),
    ]
