# Generated by Django 3.0.4 on 2020-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myorders', '0004_auto_20200502_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
