# Generated by Django 3.0.4 on 2020-05-02 03:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myorders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('Cheese', 'Cheese'), ('Italian', 'Italian'), ('Ham + Cheese', 'Ham + Cheese'), ('Meatball', 'Meatball'), ('Tuna', 'Tuna'), ('Turkey', 'Turkey'), ('Chicken Parmigiana', 'Chicken Parmigiana'), ('Eggplant Parmigiana', 'Eggplant Parmigiana'), ('Steak', 'Steak'), ('Steak + Cheese', 'Steak + Cheese'), ('Sausage, Peppers & Onions', 'Sausage, Peppers & Onions'), ('Hamburger', 'Hamburger'), ('Cheeseburger', 'Cheeseburger'), ('Fried Chicken', 'Fried Chicken'), ('Veggie', 'Veggie')], default='Cheese', max_length=30)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=7)),
                ('extra_cheese', models.BooleanField()),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorders.Order')),
                ('sub_toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_type', models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Salad w/Tuna', 'Salad w/Tuna')], default='Garden Salad', max_length=12)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platter_type', models.CharField(choices=[('Garden Salad', 'Garden Salad'), ('Greek Salad', 'Greek Salad'), ('Antipasto', 'Antipasto'), ('Baked Ziti', 'Baked Ziti'), ('Meatball Parm', 'Meatball Parm'), ('Chicken Parm', 'Chicken Parm')], default='Garden Salad', max_length=20)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=6)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_class', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], default='Regular', max_length=10)),
                ('pizza_type', models.CharField(choices=[('Cheese', 'Cheese'), ('Special', 'Special'), ('1 Topping', '1 Topping'), ('2 Toppings', '2 Toppings'), ('3 Toppings', '3 Toppings')], default='Cheese', max_length=10)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=7)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorders.Order')),
                ('pizza_toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_type', models.CharField(choices=[('Baked Ziti w/Mozzarella', 'Baked Ziti w/Mozzarella'), ('Baked Ziti w/Meatballs', 'Baked Ziti w/Meatballs'), ('Baked Ziti w/Chicken', 'Baked Ziti w/Chicken')], default='Baked Ziti w/Mozzarella', max_length=25)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myorders.Order')),
            ],
        ),
    ]
